device: "cuda" 
model: RawNet2v3
test_list: dataset/val_def.txt

nDataLoaderThread: 1 
criterion: aamsoftmax 
sample_rate: 8000
nClasses: 20000 
eval_frames: 100 
max_frames: 100 

batch_size: 32
n_mels: 64

cohorts_path: checkpoint/dump_cohorts.npy 
scoring_mode: cosine
save_path: exp/dump 
initial_model_infer: exp/dump/RawNet2v3/model/best_state_0112.model