model: RawNet2v3
lr: 0.001
nOut: 512
nClasses: 20000
weight_decay: 0
test_interval: 10
lr_decay: 0.95
preprocess: False
save_path: exp/
criterion: amsoftmax
optimizer: adam
callbacks: auto
device: 'cpu'
max_epoch: 500

sample_rate: 8000
max_frames: 100
target_format: wav
