device: "cuda" 
model: RawNet2v5
test_list: dataset/test_trial_file_converted.txt

nDataLoaderThread: 1 
criterion: softmaxproto 
sample_rate: 8000
nClasses: 20000 
eval_frames: 100 
max_frames: 100 

batch_size: 16
n_mels: 64

cohorts_path: checkpoint/dump_cohorts.npy 
scoring_mode: cosine
save_path: backup 
initial_model_infer: backup/RawNet2v5/model/best_state_107epochs.model