device: "cuda"
train_list: dataset/train_def.txt
test_list: dataset/val_def.txt
save_path: exp/dump/
model: RawNet2v3
max_epoch: 500
batch_size: 32
nDataLoaderThread: 1
criterion: aamsoftmax
nPerSpeaker: 1
n_mels: 40
margin: 0.2
scale: 30
callbacks: steplr
max_frames: 300
eval_frames: 300
sample_rate: 8000
nClasses: 20000
es_patience: 30
initial_model: exp/dump/RawNet2v3/model/best_state_0112.model
