device: "cuda" 
train_list: dataset/train_vlsp_2.txt 
test_list: dataset/val_vlsp_2.txt 
save_path: exp/dump/ 
model: RawNet2v3 
max_epoch: 1000 
batch_size: 16
nDataLoaderThread: 1 
criterion: softmaxproto 
nPerSpeaker: 2
n_mels: 40 
margin: 0.2
scale: 30
callbacks: auto 
max_frames: 100 
nClasses: 1200 
es_patience: 20 
initial_model: exp/RawNet2v3/model/best_state.model