model: ResNetSE34V2
lr: 1e-2
nOut: 512
nClasses: 400
weight_decay: 0
test_interval: 10
lr_decay: 0.95
preprocess: False
save_path: exp/
criterion: amsoftmax
optimizer: adam
callbacks: auto
device: cpu
max_epoch: 500
