device: "cuda" 
train_list: dataset/train_def.txt 
test_list: dataset/val_def.txt 
save_path: backup/
model: Raw_ECAPA
max_epoch: 500 
batch_size: 16
nDataLoaderThread: 1
criterion: softmaxproto
nPerSpeaker: 2
n_mels: 80 
margin: 0.1
scale: 30
lr: 0.001
callbacks: steplr
max_frames: 100
eval_frames: 100
sample_rate: 8000
nClasses: 20000
es_patience: 30
# initial_model: exp/dump/RawNet2v3/model/best_state_2000spk_347e-2.model