device: "cuda" 
model: Raw_ECAPA
test_threshold: 0.19424471259117126

test_path: log_service/check_log_combine/
test_list: log_service/check_log_combine/all_all.txt # private test 
ref: log_service/check_log_combine/all_all_truth.txt
com: log_service/check_log_combine/all_all_result.txt

# test_path: dataset/test_callbot_raw
# test_list: dataset/test_callbot_raw/test_cb_v1_nolb.txt # private test 
# ref: dataset/test_callbot_raw/test_cb_v1.txt
# com: dataset/test_callbot_raw/test_cb_res.txt

# test_path: log_service/cskh_test_202203/
# test_list: log_service/cskh_test_202203/ref_audio_norm.txt # private test 
# ref: log_service/cskh_test_202203/ref_audio_norm_truth.txt
# com: log_service/cskh_test_202203/ref_audio_norm_res.txt

nDataLoaderThread: 1 
criterion:   
sample_rate: 8000
nClasses: 6089 
eval_frames: 100 
max_frames: 100
num_eval: 20

batch_size: 32
n_mels: 80
step_size: 5

augment: False
test_recognize: False
cohorts_path: backup/Raw_ECAPA/cohorts_callbot.npy
scoring_mode: cosine

save_path: backup 

# initial_model_infer: backup/Raw_ECAPA/model/mix_0307_1357_v3.model # 0.5394577383995056 0.5229600071907043 0.5437501668930054
# initial_model_infer: backup/Raw_ECAPA/model/cb_0325_v1.model # 0.34933072328567505
# initial_model_infer: backup/Raw_ECAPA/model/cb_0324_ge2e_v1.model # 0.3272123336791992
# initial_model_infer: backup/Raw_ECAPA/model/cb_0329_v0.model # 0.25866398215293884
# initial_model_infer: backup/MsLoss/Raw_ECAPA/model/cb_0331_ms_am_364.model #  0.26218727231025696
initial_model_infer: backup/Raw_ECAPA/ARmSoftmax/model/best_state.model